# Generated by Django 3.0.3 on 2020-02-07 06:30

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=64, verbose_name='客户端名称')),
                ('score', models.BigIntegerField(verbose_name='分数')),
                ('create_time', models.BigIntegerField(default=common.utils.create_time_stamp, verbose_name='创建时间')),
                ('update_time', models.BigIntegerField(default=common.utils.create_time_stamp, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '客户信息 端信息和分数信息',
                'db_table': 'customer',
            },
        ),
    ]
